author_id = "lux"
app_id = "snek"
author_name = "Lux"
app_name = "Snek"

[files]
_splash = { path = "splash.png" }
font = { path = "ibm437r_8x8.fff", url = "https://fonts.fireflyzero.com/fonts/ascii/ibm437r_8x8.fff", sha256 = "aa87f0c2aa4a90a2f5c3ebd7bac2e83b2ab24c1f935fb6b5b914ebc45fbe0" }

[cheats]
move-apple = 1 # Move apple into a new random position
inc-score = 2  # Increment the score by the given value
dec-score = 3  # Decrement the score by the given value

[badges]
1 = { name = "m i tasti", descr = "bite yourself" }
2 = { name = "u r tasti", descr = "bite someone else" }
3 = { name = "apel tasti", descr = "eat 100 apples", steps = 100 }

[boards]
1 = { name = "singleplayer" }
2 = { name = "multiplayer" }
